# Generated by Django 4.2 on 2023-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='image',
            field=models.ImageField(default='no-image-icon.png', upload_to=''),
        ),
    ]
