# Generated by Django 4.2 on 2023-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='StateOfCharge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
