# Generated by Django 4.2 on 2023-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_robot_stateofcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='Location_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Location_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Location_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='task',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
