# Generated by Django 4.2 on 2023-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_robot_location_x_alter_robot_location_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='Location_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Location_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Location_z',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
