# Generated by Django 4.2 on 2023-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_robot_location_x_alter_robot_location_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('Location_x', models.IntegerField(blank=True, null=True)),
                ('Location_y', models.IntegerField(blank=True, null=True)),
                ('Location_z', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
